# Generated by Django 3.1.3 on 2020-11-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201125_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='time_without_charge',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='video',
        ),
    ]
